### ISSUE TITLE
I'm getting some errors when I try to install this.

### ISSUE THREAD

**Issue by krusion** [PassivePi/Passive_pi_earn#1]
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /usr/local/bin/python3: exec format error
```

```
$ docker-compose up -d & docker-compose logs -f
[1] 2371
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml

ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml
```

What am I doing wrong? I installed this on a raspbian 64bit image. 

Also, after installation, are there any instructions on how to use it?

**Comment by PassivePi** [comment]
Hi @krusion , are you running the commands you mention in the same folder as where the docker-compose is located? If yes, can you provide more of the logs?

**Comment by PassivePi** [comment]
@krusion , you are absolutely right. I noticed I forgot to include something, I will amend it in the future. For now, please run this command first and then proceed as illustrated in the readme:

`docker run --privileged --rm tonistiigi/binfmt --install all`

**Comment by krusion** [comment]
Hello @PassivePi 

I was traveling and just arrived today. I'll give it a shot and will update you!

Are there instructions on how to use the individual packages? Commands etc.?

**Comment by krusion** [comment]
Hello @PassivePi 

It worked! 
Now back to the usage question. I was able to set up 3 of the programs. Packetstream requires "CID". I'm not sure what that is or how to get it. I couldn't find an option for that on the website. And earnapp also requires a UUID which I wasn't able to find either. I know that with earnapp alone, it opens a link that you open with your browser and that logs you in. But not sure how to find the UUID. 

That being said, if I want to log in with my info for these apps, do I have to reinstall everything again? Or is there a command to just add the CID and UUID. And in general, are there any commands to control the apps, test the status, restart them or I have no control other than running docker and that's it? Sorry if it's trivial I can do basic stuff on linux but don't have much experience.

**Comment by PassivePi** [comment]
Hi @krusion,

The only thing which the container accomplishes, is that it generates the docker-compose.yml file for the services to run on a raspberry pi. It creates a one-off file for all services at once. That means that it does not support partial adjustments (yet). However, since it is a docker-compose file, you can of course also modify the file directly by hand.

As for the questions concering the CID and the Earnapp UUID, in this file you can see exactly which images are retrieved:
https://github.com/PassivePi/Passive_pi_earn/blob/main/passive/main.py

I invite you to go to those repositories to find more information and elaborate discussions.

PassivePi
